name: Regenerate contents.json

on:
  push:
    paths:
      - 'drafts/**'
      - 'canon/**'

jobs:
  update-contents:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any required pip packages here
        pip install -r requirements.txt
        
    - name: Run update script
      run: python gen_contents.py
        
    - name: Commit changes
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add contents.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update contents.json"
        
    - name: Push changes
      uses: ad-m/github-push-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
